547: Fix empty cancel link
GlotPress/GlotPress pull request #548
Opened 2016-09-17 17:31 UTC by toolstack

The cancel link can be blank if GP is install in the root of a domain and the permalink structure is set to have no trailing slash.

Resolves #547.

2016-09-17 19:03 UTC, ocean90 commented on gp-templates/project-new.php
> +		<span class="or-cancel"><?php _e( 'or', 'glotpress' ); ?> <a href="<?php echo gp_url_public_root(); // WPCS: XSS ok. ?>"><?php _e( 'Cancel', 'glotpress' ); ?></a></span>
XSS is not ok. 😄  Let's wrap it with `esc_url()`.

2016-09-17 19:03 UTC, ocean90 requested changes

2016-09-17 20:04 UTC, toolstack commented on gp-templates/project-new.php
> +		<span class="or-cancel"><?php _e( 'or', 'glotpress' ); ?> <a href="<?php echo gp_url_public_root(); // WPCS: XSS ok. ?>"><?php _e( 'Cancel', 'glotpress' ); ?></a></span>
Done.

2016-09-19 13:53 UTC, ocean90 approved these changes

2016-09-19 13:57 UTC, merged