554: keyboard shortcuts
GlotPress/GlotPress pull request #556
Opened 2016-09-21 21:27 UTC by toolstack

Resolves #554.

2016-09-26 10:51 UTC, akirk commented on assets/js/editor.js
> +				} else if ( 107 === e.keyCode && e.ctrlKey ) { // Ctrl-+ = Approve.
`Ctrl-+` zooms in the webpage in most browsers in Windows, see [Windows > Webpage shortcuts > Make everything on the page bigger](https://support.google.com/chrome/answer/157179)

2016-09-26 10:51 UTC, akirk commented on assets/js/editor.js
> +				} else if ( 109 === e.keyCode && e.ctrlKey ) { // Ctrl-- = Reject.
Same as above, `Ctrl--` zooms out the webpage in most browsers in Windows.

2016-09-26 10:57 UTC, ocean90 commented on assets/js/editor.js
> +				} else if ( 33 === e.keyCode || ( 38 === e.keyCode && e.ctrlKey ) ) { // Page Down or Ctrl-Up Arrow = Previous editor.
CTRL-[UP/DOWN/LEFT/RIGHT] are used by OS X to open Mission Control and to change spaces.

2016-09-26 10:57 UTC, akirk commented on assets/js/editor.js
> +				} else if ( 109 === e.keyCode && e.ctrlKey ) { // Ctrl-- = Reject.
What about `Cmd+Shift+r` resp. `Ctrl+Shift+r`?

2016-09-26 10:58 UTC, akirk commented on assets/js/editor.js
> +				} else if ( 107 === e.keyCode && e.ctrlKey ) { // Ctrl-+ = Approve.
What about `Cmd+Shift+a` resp. `Ctrl+Shift+a`?

2016-09-26 11:55 UTC, toolstack commented on assets/js/editor.js
> +				} else if ( 107 === e.keyCode && e.ctrlKey ) { // Ctrl-+ = Approve.
I think we'll never avoid all shortcuts used by every os or user, we already hijack PgUp/PgDn.  This is also only active within the editor box, so I don't see it as a big deal.

2016-09-26 11:56 UTC, toolstack commented on assets/js/editor.js
> +				} else if ( 109 === e.keyCode && e.ctrlKey ) { // Ctrl-- = Reject.
See above.

2016-09-26 11:56 UTC, toolstack commented on assets/js/editor.js
> +				} else if ( 33 === e.keyCode || ( 38 === e.keyCode && e.ctrlKey ) ) { // Page Down or Ctrl-Up Arrow = Previous editor.
See above.

2016-09-26 16:44 UTC, GaryJones commented
I'm not fussed with the keyboard shortcuts for Approve and Reject right now, since they are often done with the bulk checkboxes. It's

2016-09-26 21:11 UTC, toolstack commented
@GaryJones I wouldn't want to change an existing shortcut and replace it with something else, that would be confusing for the users.

2016-10-11 09:31 UTC, ocean90 requested changes

2016-10-11 09:31 UTC, ocean90 commented on gp-templates/helper-functions.php
> +				printf( __( 'You <a href="%s">have to log in</a> to edit this translation.', 'glotpress' ), esc_url( wp_login_url() ) );
This reverts a previous commit.

2016-10-11 09:49 UTC, ocean90 commented on assets/js/editor.js
> +				} else if ( ( 13 === e.keyCode && e.ctrlKey ) || ( 66 === e.keyCode && e.shiftKey && e.ctrlKey ) ) { // Ctrl-Enter or Ctrl-Shift-B = Copy original.
Shouldn't this just trigger a click event for `a.copy` so that the `copy()` method gets used?

2016-10-11 12:15 UTC, toolstack commented on gp-templates/helper-functions.php
> +				printf( __( 'You <a href="%s">have to log in</a> to edit this translation.', 'glotpress' ), esc_url( wp_login_url() ) );
Not sure how that slipped in there... will undo it.

2016-10-11 12:17 UTC, toolstack commented on assets/js/editor.js
> +				} else if ( ( 13 === e.keyCode && e.ctrlKey ) || ( 66 === e.keyCode && e.shiftKey && e.ctrlKey ) ) { // Ctrl-Enter or Ctrl-Shift-B = Copy original.
It could, I'll update the code.

2016-10-11 15:17 UTC, ocean90 requested changes

2016-10-11 15:17 UTC, ocean90 commented on assets/js/editor.js
> +					target = $( e.target );
`target` is unused.

2016-10-11 15:17 UTC, ocean90 commented on assets/js/editor.js
> +					target = $( e.target );
`target` is unused.

2016-10-18 16:07 UTC, ocean90 approved these changes

2016-10-18 16:07 UTC, merged

2016-10-18 23:02 UTC, GaryJones commented
This is awesome - thank you so much for merging this - it's going to save `en_*` translators about half the time reckon!