Add JSON formats
GlotPress/GlotPress pull request #567
Opened 2016-10-03 06:20 UTC by swissspidy

This integrates the [glotpress-json](https://github.com/swissspidy/glotpress-json) plugin I've been working on into GlotPress.

Adds two new formats (including tests):

* `GP_Format_JSON`: "simple" JSON (key -> value)
* `GP_Format_Jed1x`: Jed 1.x compatible format, extends `GP_Format_JSON`

As you can see, the `GP_Format_JSON` class is easily extensible for more specific use cases. See swissspidy/glotpress-json#4 for some background.

Fixes #523.

2016-10-03 06:20 UTC, swissspidy commented
Note: Because both formats use the `.json` file extension, `test_gp_get_import_file_format()` currently fails. Any ideas welcome.

2016-10-03 11:21 UTC, ocean90 commented
>  `test_gp_get_import_file_format()` currently fails. 

Maybe `gp_get_import_file_format()` needs to be changed to return an array of formats if multiple formats exist for a file extension. In `GP_Route_Translation::import_translations_post()` the import should then be canceled if the extension is ambiguous. @toolstack What do you think?

2016-10-03 12:06 UTC, toolstack commented
> > test_gp_get_import_file_format() currently fails. 

> Maybe gp_get_import_file_format() needs to be changed to return an array of formats if multiple formats exist for a file extension. In GP_Route_Translation::import_translations_post() the import should then be canceled if the extension is ambiguous. @toolstack What do you think?

I don't like the idea of returning an array as it could break many perfectly useable cases.  We already have this in the Android/ResX formats, both use .xml as their file extension, but we use .resx.xml for ResX.

I'd change the extension name for the JED files to something like ".jed1x.json" so they can be identified uniquely.  Or if we think JED is the more widely used format, change the base class to ".raw.json" or something similar.

2016-10-04 15:38 UTC, ocean90 commented
@toolstack Interesting, I wasn't aware of that. Isn't .resx also an extension for the ResX format? Should we update the name property for the dropdown?

<img width="327" alt="format-dropdown" src="https://cloud.githubusercontent.com/assets/617637/19081042/34c31b26-8a59-11e6-9b9b-d7cc99ac843e.png">

2016-10-04 17:13 UTC, toolstack commented
@ocean90 Yea, I found out about it when I was doing the auto detection code.  Looks like .resx is a valid extension so we should update it, I'll create a PR once we merge the file rename PR.

2016-10-04 17:17 UTC, swissspidy commented
OK, so changing the extensions sounds like an easy solution. I'd go for `.jed.json` or `.jed1x.json` in that case

2016-10-10 06:48 UTC, swissspidy commented
Just to let you know, this PR now adds meta data to the Jed 1.x format as discussed in swissspidy/glotpress-json#4.

2016-10-10 11:29 UTC, ocean90 requested changes
There are some missing `@return` descriptions and I suggest to rename `GP_Format_JSON::json_encode()`.

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-jed1x.php
> +	 * @return array|false The encoded value or fals on failure.
Typo: `fals` => `false`

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-json.php
> +	 * @return string
Missing description.

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-json.php
> +	 * @return Translations|bool
Missing description.

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-json.php
> +	 * @return Translations
Missing description.

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-json.php
> +	 * @return array|false The encoded value or fals on failure.
Typo: `fals` => `false`

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-jed1x.php
> +	 * @return Translations|bool
Missing description.

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-jed1x.php
> +		 * @see https://bugs.php.net/bug.php?id=50867
`@see` should be `@link`

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-jed1x.php
> +		 * Replace '__GP_EMPTY__' with an acttual empty string.
Typo: `acttual` => `actual`

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-jed1x.php
> +	 * @return string
Missing description.

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-jed1x.php
> +	 * @param GP_Locale          $locale          The locale object the strings are being exported for. not used
Typo: `for. not used` => `for, not used` (comma)

2016-10-10 11:29 UTC, ocean90 commented on gp-includes/formats/format-json.php
> +	 * Decodes a JSON string.
I think the summary should mention that the methods reads the content of a file and then decodes the content. Maybe the name of the method should reflect that too: `decode_json_file( $file_name)`

2016-10-10 12:14 UTC, swissspidy commented
@ocean90 Thanks for the review. I've addressed these points now.

2016-10-10 13:47 UTC, ocean90 approved these changes
LGTM.

2016-10-11 09:29 UTC, merged