Add hook for adding links to the translation editor
GlotPress/GlotPress pull request #587
Opened 2016-10-20 13:58 UTC by akirk

With this hook links can be added to the "More Links" section in the translation editor, for example on WordPress.com we have [this view](https://translate.wordpress.com/projects/wpcom/-all-translated/212430/) that we link like this:

![screen shot 2016-10-20 at 15 50 21](https://cloud.githubusercontent.com/assets/203408/19562713/a12f2760-96dd-11e6-8ee7-82c9a32a9622.png)

2016-10-20 17:21 UTC, toolstack commented
Would it make more sense to be able to filter a list of links for the more list instead of just outputting additional ones at the end?

That way you could reorder them or add items at the top or between existing ones.

2016-10-20 19:44 UTC, akirk commented
I like that and have updated the PR accordingly.

2016-10-25 22:34 UTC, ocean90 requested changes

2016-10-25 22:34 UTC, ocean90 commented on gp-templates/translation-row.php
> +					foreach ( apply_filters( 'gp_translation_row_template_more_links', $more_links, $project, $locale, $translation_set, $t ) as $link => $title ) : ?>
* Code indentation looks a bit off here.
* The `@param` tags should be aligned.
* The `title` attribute should be removed. #a11y

2016-11-03 13:09 UTC, ocean90 commented
Instead of using the URL as the key I suggest to use a simple string like `permalink` or `originals-across-locales`. This makes it easier to remove existing links. The value would be the HTML markup for a link.

2016-11-03 14:30 UTC, ocean90 commented on gp-templates/translation-row.php
> +						<li><?php echo wp_kses( $link, array( 'a' => array( 'href' ) ) ); ?></li>
Why the use of `wp_kses()` here? It's not really necessary since there is no direct user input.

2016-11-03 14:34 UTC, ocean90 requested changes

2016-11-03 14:34 UTC, ocean90 commented on gp-templates/translation-row.php
> +						<li><?php echo wp_kses( $link, array( 'a' => array( 'href' ) ) ); ?></li>
Why the use of wp_kses() here? It's not really necessary since there is no direct user input.

2016-11-03 14:34 UTC, ocean90 commented on gp-templates/translation-row.php
> +	);
> PHP Parse error:  syntax error, unexpected ')' in gp-templates/translation-row.php on line 22

2016-11-03 14:34 UTC, ocean90 commented on gp-templates/translation-row.php
> +	$more_links['translation-permalink'] = '<a tabindex="-1" href="' . esc_attr( $translation_permalink ). '">' . __( 'Permalink to this translation', 'glotpress' ) . '</a>';
Shouldn't `esc_attr()` be `esc_url()`?

2016-11-03 14:34 UTC, ocean90 commented on gp-templates/translation-row.php
> +				     * @since 2.3
Version numbers should use three digits, `2.3.0`.

2016-11-03 14:34 UTC, ocean90 commented on gp-templates/translation-row.php
> +					foreach ( apply_filters( 'gp_translation_row_template_more_links', $more_links, $project, $locale, $translation_set, $t ) as $link ) : ?>
To make the code more readable the filter should be moved out of the loop expression. The code indentation stills looks wrong.

2016-11-03 14:50 UTC, akirk commented on gp-templates/translation-row.php
> +						<li><?php echo wp_kses( $link, array( 'a' => array( 'href' ) ) ); ?></li>
After discussion on #glotpress, I'm adding a `// WPCS: XSS ok.` here.

2016-11-03 15:11 UTC, ocean90 approved these changes

2016-11-03 18:30 UTC, ocean90 requested changes

2016-11-03 18:30 UTC, ocean90 commented on gp-templates/translation-row.php
> +	$more_links['translation-permalink'] = '<a tabindex="-1" href="' . esc_attr( $translation_permalink ) . '">' . __( 'Permalink to this translation', 'glotpress' ) . '</a>';
This is still using `esc_attr()` 🤔

2016-11-06 14:31 UTC, ocean90 approved these changes

2016-11-06 14:46 UTC, merged