Add HHVM and nightly PHP to travis config
GlotPress/GlotPress pull request #593
Opened 2016-11-01 11:28 UTC by atimmer

They are allowed to fail because they can be flaky, but it is still
nice to be able to see their build status.

2016-11-01 11:30 UTC, swissspidy approved these changes

2016-11-01 11:33 UTC, swissspidy commented
Looks like the tests aren't running on HHVM at all: https://travis-ci.org/GlotPress/GlotPress-WP/jobs/172258752

2016-11-03 13:12 UTC, ocean90 requested changes
Needs a rebase for .travis.yml.

2016-11-03 13:37 UTC, atimmer commented
@ocean90 Done.

2016-11-03 13:40 UTC, ocean90 approved these changes

2016-11-03 13:40 UTC, merged