Add filter for the locale glossary path prefix
GlotPress/GlotPress pull request #669
Opened 2017-02-21 19:52 UTC by ocean90

Fixes #655.

2017-02-21 21:16 UTC, toolstack requested changes

2017-02-21 21:16 UTC, toolstack commented on gp-includes/things/glossary.php
> +		$locale_glossary_prefix = apply_filters( 'gp_locale_glossary_path_prefix', '/languages' );
Missing filter docblock

2017-02-21 21:16 UTC, toolstack commented on gp-includes/things/glossary.php
> +			'path' => "/$locale_glossary_prefix",
Not sure why the second slash is there, but should we filter it as well?

2017-02-21 21:16 UTC, toolstack commented on gp-includes/things/project.php
> +		$locale_glossary_prefix = apply_filters( 'gp_locale_glossary_path_prefix', '/languages' );
Missing filter docblock

2017-02-21 21:19 UTC, ocean90 commented on gp-includes/things/glossary.php
> +			'path' => "/$locale_glossary_prefix",
That's a hack for https://github.com/GlotPress/GlotPress-WP/blob/2.3.0/gp-includes/url.php#L149 :)

2017-02-21 21:44 UTC, toolstack commented on gp-includes/things/glossary.php
> +		 * @since 2.3.1
Probably 2.4?

2017-02-21 21:44 UTC, toolstack commented on gp-includes/things/project.php
> +		 * @since 2.3.1
Probably 2.4?

2017-02-21 21:44 UTC, toolstack commented on gp-includes/things/glossary.php
> +			'path' => "/$locale_glossary_prefix",
:+1:

2017-02-21 21:46 UTC, ocean90 commented on gp-includes/things/project.php
> +		 * @since 2.3.1
@toolstack Nope, that's for the 2.3.1 milestone.

2017-02-21 21:48 UTC, toolstack approved these changes

2017-02-21 21:54 UTC, merged

2017-02-22 08:47 UTC, akirk commented on gp-includes/things/glossary.php
> +			'path' => "/$locale_glossary_path_prefix",
This will lead to a double-slashed path (because the default variable content is /languages). Is that intentional?

2017-02-22 08:48 UTC, ocean90 commented on gp-includes/things/glossary.php
> +			'path' => "/$locale_glossary_path_prefix",
@akirk That's your code! 😉 https://github.com/GlotPress/GlotPress-WP/pull/669#discussion_r102319616

2017-02-22 08:49 UTC, akirk commented on gp-includes/things/glossary.php
> +			'path' => "/$locale_glossary_path_prefix",
I'll add a comment :)

2017-02-22 08:59 UTC, akirk commented on gp-includes/things/glossary.php
> +			'path' => "/$locale_glossary_path_prefix",
https://github.com/GlotPress/GlotPress-WP/pull/671